//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMaleabAlKorbV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int messageNo { get; set; }
        public string name { get; set; }
        public string emails { get; set; }
        public string allMessage { get; set; }
        public Nullable<System.DateTime> dateMessage { get; set; }
    }
}
