//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMaleabAlKorbV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int playerNo { get; set; }
        public string names { get; set; }
        public string emails { get; set; }
        public string passwords { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    }
}
