//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMaleabAlKorbV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class playerDeleteData
    {
        public int id { get; set; }
        public string allData { get; set; }
    }
}
